# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 10800560c025a3b5e966e077757c48298d8c006765dba730898f45e82576d977d7edacbd7f5858e8382e4e00c890c87869aac065f994fd4d8a5b41f19040f763

test:
  secret_key_base: ed4198e9c34fdf49cdd9bca105bc7092223ad41e6513e8aaa07cfc9fbf59d1cda5446874ab19c52177d18e46df32426042bd537fef0a6484aa7b4bd38d8bd73e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
